---
services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    container_name: vaultwarden
    volumes:
      - ../data/:/data/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN_HASHED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - 'traefik.http.routers.vaultwarden.rule=Host("vaultwarden.leonidgrishenkov.com")'
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=frontend"
      # - "traefik.http.routers.vaultwarden.middlewares=auth" doesn't work

networks:
  frontend:
    external: true
